Fix azureai model provider (#949)
* Fix azureai model provider

I was running into a validation error if the model produced an empty assistant message (was set to None rather than an empty string, and this is apparently invalid). This should fix that.

Error below:

```
Traceback (most recent call last):
  File "/home/ubuntu/tiny-agents/.venv/lib/python3.12/site-packages/inspect_ai/model/_providers/azureai.py", line 366, in chat_completion_assistant_message
    return ChatMessageAssistant(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tiny-agents/.venv/lib/python3.12/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ChatMessageAssistant
content.str
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
content.list[union[ContentText,ContentImage]]
  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/list_type
```

* Update CHANGELOG.md

---------

Co-authored-by: jjallaire-aisi <joseph.allaire@dsit.gov.uk>